export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_STARTED = 'SEARCH_STARTED';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
